### ISSUE TITLE
Add CheckResult type and functions to ListCheckResults & RetrieveCheckResult

### ISSUE THREAD

**Issue by ogbuaguno** [checkly/checkly-go-sdk#5]
We have a use case of the checkly sdk where we need to retrieve the last check result to update the state of the server. In order to achieve this, the following needs to be added:

1. A type on `CheckResult` to model the response of this request https://www.checklyhq.com/docs/api/#retrieve-a-check-result. 
2. A function that makes the call to the above endpoint to retrieve a check request
3. A function that makes a call to the endpoint https://www.checklyhq.com/docs/api/#lists-all-check-results to retrieve a list of all check requests for a check

**Comment by kjda** [comment]
thanks @ogbuaguno I'll be working on this today/tomorrow
