### ISSUE TITLE
Create new methods for checks CRUD

### ISSUE THREAD

**Issue by ianaya89** [checkly/checkly-go-sdk#71]
- Flag existing methods as deprecated 
- Add more verbose method names (with the same functionality) to be consistent with the other resources:
   ```
   CreateCheck
   UpdateCheck
   DeleteCheck
   GetCheck
   ```
- Use new check create endpoints for check creation

**Comment by pilimartinez** [comment]
@ianaya89 the README examples are using the old method names (create, delete, update, get) should I add a deprecation warning and a suggestion to use the new ones? or just change the examples for the new ones with no deprecation warning? (the user will still have access to the old methods, but they are not going to be on the readme examples)
