### ISSUE TITLE
Release v1.5.7?

### ISSUE THREAD

**Issue by akosveres** [checkly/checkly-go-sdk#97]
Hi,

Could you please release v1.5.7? I see an important change, which is https://github.com/checkly/checkly-go-sdk/commit/b5ee1078ff8c6d1c4cfb7cf29cfa35b3b37a6463#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR15.

Or can you advise when the next release is expected? Sorry if it's already planned and I'm just jumping the gun.

**Comment by ianaya89** [comment]
Hi @akosveres, version v1.5.7 was already shipped but tagged as pre-release. I just edited it and made it fully available.
Hope that helps.
